application: secrets-app
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css
  secure: always
  
- url: /images
  static_dir: images
  secure: always
  
- url: /script
  static_dir: script
  secure: always
  
- url: /static
  static_dir: static
  secure: always
  
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /.*
  script: main.py
  secure: always

